#include <catch2/catch_all.hpp>

#include "test_helpers.hpp"

#include <cmath>
#include <cctype>
#include <sstream>

using namespace Slic3r;
using namespace Slic3r::Test;

namespace {

std::string strip_generated_timestamp(std::string gcode)
{
    const size_t begin = gcode.find("; generated by ");
    if (begin != std::string::npos) {
        const size_t end = gcode.find('\n', begin);
        gcode.erase(begin, end == std::string::npos ? std::string::npos : end - begin + 1);
    }
    return gcode;
}

// Compare two exports line by line, skipping wall-clock-dependent header lines, and report the
// first divergence precisely (a whole-file compare is undebuggable in CI output).
void require_equivalent_gcode(const std::string &lhs, const std::string &rhs)
{
    const auto volatile_line = [](const std::string &line) {
        // M73 progress/remaining-time annotations are estimator metadata, not geometry; the
        // estimator's rounding differs across platforms. Geometry differences still surface
        // through the G1 lines themselves.
        return line.rfind("M73 ", 0) == 0 ||
               line.rfind("; estimated printing time", 0) == 0 ||
               line.rfind("; prepare time", 0) == 0 ||
               line.rfind("; total estimated time", 0) == 0 ||
               line.rfind("; model printing time", 0) == 0;
    };
    // Object-label ids are process-global counters, unstable across Print instantiations and
    // test execution order; the label text itself is what must match.
    const auto normalize = [](std::string line) {
        if (line.rfind("; printing object", 0) == 0 || line.rfind("; stop printing object", 0) == 0) {
            const size_t id = line.find(" id:");
            if (id != std::string::npos) {
                size_t end = id + 4;
                while (end < line.size() && std::isdigit(static_cast<unsigned char>(line[end])))
                    ++end;
                line.erase(id, end - id);
            }
        }
        return line;
    };
    std::istringstream ls(lhs), rs(rhs);
    std::string ll, rl;
    size_t line_no = 0;
    while (true) {
        bool lok = bool(std::getline(ls, ll));
        bool rok = bool(std::getline(rs, rl));
        while (lok && volatile_line(ll)) lok = bool(std::getline(ls, ll));
        while (rok && volatile_line(rl)) rok = bool(std::getline(rs, rl));
        ++line_no;
        if (!lok || !rok) {
            INFO("uneven line counts near line " << line_no);
            REQUIRE(lok == rok);
            return;
        }
        ll = normalize(ll);
        rl = normalize(rl);
        if (ll != rl) {
            INFO("first differing line " << line_no << ":\n  baseline: " << ll << "\n  expanded: " << rl);
            REQUIRE(ll == rl);
            return;
        }
    }
}

double header_width(const std::string &gcode, const std::string &label)
{
    const std::string prefix = "; " + label + " extrusion width = ";
    const size_t begin = gcode.find(prefix);
    REQUIRE(begin != std::string::npos);
    return std::stod(gcode.substr(begin + prefix.size()));
}

DynamicPrintConfig role_width_config(const char *outer_widths, const char *sparse_widths)
{
    return mixed_nozzle_config({
        {"outer_wall_filament_id", 2},
        {"inner_wall_filament_id", 2},
        {"sparse_infill_filament_id", 1},
        {"outer_wall_line_width", outer_widths},
        {"sparse_infill_line_width", sparse_widths},
        {"sparse_infill_density", "15%"},
        {"sparse_infill_process_layer_height", 0.1},
    });
}

} // namespace

TEST_CASE("Uniform-nozzle scalar width presets keep byte-identical G-code", "[LineWidthVariants][Regression]")
{
    DynamicPrintConfig baseline = multifilament_config(2, {
        {"nozzle_diameter", "0.4,0.4"},
        {"outer_wall_filament_id", 1},
        {"inner_wall_filament_id", 1},
        {"sparse_infill_filament_id", 2},
        {"skirt_loops", 0},
    });
    baseline.set_key_value("gcode_comments", new ConfigOptionBool(true));
    DynamicPrintConfig reparsed = baseline;
    for (const char *key : {
             "line_width", "outer_wall_line_width", "inner_wall_line_width", "sparse_infill_line_width",
             "internal_solid_infill_line_width", "top_surface_line_width", "skin_infill_line_width",
             "skeleton_infill_line_width", "support_line_width", "initial_layer_line_width"}) {
        reparsed.set_deserialize_strict(key, baseline.option_throw(key)->serialize());
        auto *widths = reparsed.option<ConfigOptionFloatsOrPercentsNullable>(key);
        REQUIRE(widths != nullptr);
        const FloatOrPercent broadcast = widths->get_at(0);
        widths->values = {broadcast, broadcast};
    }

    Print baseline_print;
    Model model;
    init_print({cube(20.)}, baseline_print, model, baseline);

    Print expanded_print;
    expanded_print.apply(model, reparsed);
    expanded_print.validate();
    expanded_print.set_status_silent();

    require_equivalent_gcode(strip_generated_timestamp(gcode(baseline_print)),
                             strip_generated_timestamp(gcode(expanded_print)));
}

TEST_CASE("Mixed tools use the line width column for each extrusion role", "[LineWidthVariants][GCode]")
{
    Print print;
    Model model;
    init_print({cube(20.)}, print, model, role_width_config("0.44,0.22", "0.45,0.25"));
    const std::string gcode_output = gcode(print);
    CHECK_THAT(header_width(gcode_output, "external perimeters"), Catch::Matchers::WithinAbs(0.22, 1e-6));
    CHECK_THAT(header_width(gcode_output, "infill"), Catch::Matchers::WithinAbs(0.45, 1e-6));
}

TEST_CASE("Percent line widths resolve against their role tool nozzle", "[LineWidthVariants][GCode][Percent]")
{
    const std::string gcode_output = slice({cube(20.)}, role_width_config("125%,125%", "125%,125%"));
    CHECK_THAT(header_width(gcode_output, "external perimeters"), Catch::Matchers::WithinAbs(0.5, 1e-6));
    CHECK_THAT(header_width(gcode_output, "infill"), Catch::Matchers::WithinAbs(0.25, 1e-6));
}

TEST_CASE("Scalar width presets broadcast and explicit object values win", "[LineWidthVariants][Config]")
{
    DynamicPrintConfig scalar = DynamicPrintConfig::full_print_config();
    scalar.set_deserialize_strict("outer_wall_line_width", "0.33");
    const auto *scalar_width = scalar.option<ConfigOptionFloatsOrPercentsNullable>("outer_wall_line_width");
    REQUIRE(scalar_width != nullptr);
    REQUIRE(scalar_width->values.size() == 1);
    CHECK_THAT(scalar_width->get_at(0).value, Catch::Matchers::WithinAbs(0.33, 1e-9));
    CHECK_THAT(scalar_width->get_at(7).value, Catch::Matchers::WithinAbs(0.33, 1e-9));

    DynamicPrintConfig config = role_width_config("0.44,0.22", "0.45,0.25");
    Model model;
    ModelObject *object = model.add_object("cube", "", cube(20.));
    object->config.set_key_value("outer_wall_line_width", new ConfigOptionFloatOrPercent(0.5, false));
    object->add_instance();
    object->ensure_on_bed();

    Print print;
    print.apply(model, config);
    const auto &object_widths = print.objects().front()->printing_region(0).config().outer_wall_line_width;
    CHECK_THAT(object_widths.get_at(0).value, Catch::Matchers::WithinAbs(0.5, 1e-9));
    CHECK_THAT(object_widths.get_at(1).value, Catch::Matchers::WithinAbs(0.5, 1e-9));

    object->volumes.front()->config.set_key_value(
        "outer_wall_line_width",
        new ConfigOptionFloatsOrPercentsNullable{{0.6, false}, {0.7, false}});
    print.apply(model, config);
    const auto &volume_widths = print.objects().front()->printing_region(0).config().outer_wall_line_width;
    CHECK_THAT(volume_widths.get_at(0).value, Catch::Matchers::WithinAbs(0.6, 1e-9));
    CHECK_THAT(volume_widths.get_at(1).value, Catch::Matchers::WithinAbs(0.7, 1e-9));
}

TEST_CASE("Filament projections update only the selected role slot", "[LineWidthVariants][Projection]")
{
    DynamicPrintConfig config = role_width_config("0.42,0.42", "0.42,0.42");
    config.option<ConfigOptionStrings>("filament_process_projection", true)->values = {
        "outer_wall_line_width=0.44;sparse_infill_line_width=0.45",
        "outer_wall_line_width=0.22;sparse_infill_line_width=0.25",
    };
    Print print;
    Model model;
    init_print({cube(20.)}, print, model, config);

    const PrintRegionConfig &region = print.objects().front()->printing_region(0).config();
    CHECK_THAT(region.outer_wall_line_width.get_at(0).value, Catch::Matchers::WithinAbs(0.42, 1e-9));
    CHECK_THAT(region.outer_wall_line_width.get_at(1).value, Catch::Matchers::WithinAbs(0.22, 1e-9));
    CHECK_THAT(region.sparse_infill_line_width.get_at(0).value, Catch::Matchers::WithinAbs(0.45, 1e-9));
    CHECK_THAT(region.sparse_infill_line_width.get_at(1).value, Catch::Matchers::WithinAbs(0.42, 1e-9));
}

TEST_CASE("Width validation reads only the role tool slot", "[LineWidthVariants][Validate]")
{
    DynamicPrintConfig pass_config = role_width_config("0.01,0.22", "0.45,0.25");
    Print pass_print;
    Model pass_model;
    init_print({cube(20.)}, pass_print, pass_model, pass_config);
    const StringObjectException pass_error = pass_print.validate();
    INFO(pass_error.string);
    CHECK(pass_error.string.empty());

    DynamicPrintConfig fail_config = role_width_config("0.44,0.1", "0.45,0.25");
    Print fail_print;
    Model fail_model;
    init_print({cube(20.)}, fail_print, fail_model, fail_config);
    const StringObjectException error = fail_print.validate();
    INFO(error.string);
    REQUIRE_FALSE(error.string.empty());
    CHECK(error.opt_key == "outer_wall_line_width");
    CHECK(error.string.find("Line width too small") != std::string::npos);
}
